export default {
  contColor: "#efefef",
  brdColor: "#D7D7D7",
  brdActiveColor: "#2AA97D",
  drawerColor: "#FAFAFA",
  shColor: "rgba(0, 0, 0, 0.08)",
  errColor: "red",
  cardBackColor: "#FAFAFA",
  fontColor: "#517468",
  fontLightColor: "#B0BFBA",
  fontBoldColor: "#0B3C2B",
  blackColor: "black",
  btnBackColor: "#313d49",
  inputBackColor: "#d7e0da",
  inputBrdColor: "#D1D1D1",
  headerColor: "#70b88b",
  drawerBckColor: "#FAFAFA",
  greenColor: "#009965",
  whiteColor: "#FFFFFF",
  iconColor: "#759087",
  iconActiveColor: "#5ABC9B",
  iconBlurColor: "#C6D1CE",
  tagColor: "#FFFFFF",
  delColor: "#FC5C65",
  fmColor: "#B7E9DD",
  bdColor: "#E6BACD",
  grColor: "#C8E6C9",
  fruitColor: "#FFE0B2",
  nrnColor: "#C03125",
};
